openapi: 3.0.3
info:
  title: Сервис тренировок
  version: 1.0.0
  description: API для управления тренировками, упражнениями, отслеживания прогресса и аналитики пользователей.

servers:
  - url: https://api.workout-service.com/v1

paths:
  /workouts:
    post:
      summary: Создать новую тренировку
      description: Указав определенную дату можно запланировать тренировку
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WorkoutCreateRequest'
      responses:
        '201':
          description: Тренировка успешно создана
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Workout'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'

    get:
      summary: Получить список тренировок пользователя
      responses:
        '200':
          description: Список тренировок
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Workout'
        '401':
          $ref: '#/components/responses/Unauthorized'

  /workouts/{workoutId}:
    get:
      summary: Получить тренировку по ID
      parameters:
        - name: workoutId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Тренировка найдена
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Workout'
        '404':
          $ref: '#/components/responses/NotFound'

  /exercises:
    post:
      summary: Добавить новое упражнение
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ExerciseCreateRequest'
      responses:
        '201':
          description: Упражнение успешно добавлено
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Exercise'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'

  /progress:
    post:
      summary: Зафиксировать прогресс
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProgressCreateRequest'
      responses:
        '201':
          description: Прогресс успешно зафиксирован
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Progress'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'

    get:
      summary: Получить историю занятий пользователя
      responses:
        '200':
          description: История занятий
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Progress'
        '401':
          $ref: '#/components/responses/Unauthorized'

  /analytics/improvement:
    get:
      summary: Получить аналитику по улучшению
      responses:
        '200':
          description: Аналитика по улучшению
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ImprovementAnalytics'
        '401':
          $ref: '#/components/responses/Unauthorized'
          
  /me:
    get:
      summary: Получить профиль текущего пользователя
      responses:
        '200':
          description: Профиль пользователя
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '401':
          $ref: '#/components/responses/Unauthorized'

components:
  schemas:
    User:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        email:
          type: string
          format: email

    Workout:
      type: object
      required:
        - id
        - title
        - userId
        - date
      properties:
        id:
          type: integer
          format: int64
        userId:
          type: integer
          format: int64
        title:
          type: string
        description:
          type: string
        date:
          type: string
          format: date
        exercises:
          type: array
          items:
            $ref: '#/components/schemas/Exercise'

    WorkoutCreateRequest:
      type: object
      required:
        - title
        - date
      properties:
        title:
          type: string
          minLength: 1
        description:
          type: string
        date:
          type: string
          format: date

    Exercise:
      type: object
      required:
        - id
        - name
        - type
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        type:
          type: string
          enum: [strength, cardio, flexibility, endurance]
        targetMuscle:
          type: string
        description:
          type: string

    ExerciseCreateRequest:
      type: object
      required:
        - name
        - type
      properties:
        name:
          type: string
          minLength: 1
        type:
          type: string
          enum: [strength, cardio, flexibility, endurance]
        targetMuscle:
          type: string
        description:
          type: string
        workoutId:
          type: integer
          format: int64

    Progress:
      type: object
      required:
        - id
        - userId
        - exerciseId
        - workoutId
        - timestamp
        - sets
      properties:
        id:
          type: integer
          format: int64
        userId:
          type: integer
          format: int64
        workoutId:
          type: integer
          format: int64
        exerciseId:
          type: integer
          format: int64
        timestamp:
          type: string
          format: date-time
        sets:
          type: array
          items:
            type: object
            required:
              - repetitions
              - weightKg
            properties:
              repetitions:
                type: integer
                minimum: 1
              weightKg:
                type: number
                format: float
                minimum: 0

    ProgressCreateRequest:
      type: object
      required:
        - exerciseId
        - sets
      properties:
        exerciseId:
          type: integer
          format: int64
        workoutId:
          type: integer
          format: int64
        sets:
          type: array
          minItems: 1
          items:
            type: object
            required:
              - repetitions
              - weightKg
            properties:
              repetitions:
                type: integer
                minimum: 1
              weightKg:
                type: number
                format: float
                minimum: 0

    ImprovementAnalytics:
      type: object
      properties:
        userId:
          type: integer
          format: int64
        periodStart:
          type: string
          format: date
        periodEnd:
          type: string
          format: date
        improvements:
          type: array
          items:
            type: object
            properties:
              exerciseId:
                type: integer
                format: int64
              exerciseName:
                type: string
              maxWeightKg:
                type: number
                format: float
              avgRepetitions:
                type: number
                format: float
              improvementPercent:
                type: number
                format: float

    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: string
        message:
          type: string
        details:
          type: object
          additionalProperties: true

  responses:
    BadRequest:
      description: Неверный запрос (ошибки валидации, отсутствующие поля и т.п.)
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

    Unauthorized:
      description: Пользователь не авторизован
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

    NotFound:
      description: Ресурс не найден
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'